# Generated by Django 5.1.7 on 2025-03-30 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('national_code', models.CharField(max_length=10, unique=True)),
                ('age', models.IntegerField()),
                ('total_toll_paid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('width', models.FloatField()),
                ('geom', models.TextField(null=True)),
                ('users', models.ManyToManyField(related_name='roads', to='amin.user')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('length', models.FloatField()),
                ('load_valume', models.FloatField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerCar', to='amin.user')),
            ],
        ),
    ]
