# Generated by Django 5.1.7 on 2025-03-30 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amin.car')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amin.road')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amin.user')),
            ],
            options={
                'unique_together': {('user', 'car', 'road')},
            },
        ),
    ]
