# Generated by Django 5.1.7 on 2025-04-01 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amin', '0004_toll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlocation',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='amin.car'),
        ),
        migrations.DeleteModel(
            name='Toll',
        ),
    ]
