# Generated by Django 5.1.7 on 2025-04-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amin', '0006_tollstation_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TollStationAndVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('toll_per_cross', models.PositiveIntegerField()),
                ('car_id', models.PositiveIntegerField(unique=True)),
                ('owner_national_code', models.CharField(max_length=10)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('bus', 'Bus')], max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('nearest_toll', models.PositiveIntegerField()),
                ('distance_to_nearest_toll', models.PositiveIntegerField()),
                ('unpaid_toll', models.PositiveIntegerField(default=0)),
                ('overdue_toll', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='nearest_toll',
        ),
        migrations.DeleteModel(
            name='TollStation',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
